handle malformed

diff --git a/.github/workflows/conbench_upload.yml b/.github/workflows/conbench_upload.yml
--- a/.github/workflows/conbench_upload.yml
+++ b/.github/workflows/conbench_upload.yml
@@ -94,7 +94,13 @@ jobs:
       run: |
         unzip benchmark-results.zip -d benchmark-results
         unzip pr_number.zip
-        echo "pr_number=$(grep -ox '[[:digit:]]*' pr_number.txt)" >> $GITHUB_OUTPUT
+        pr_number=$(grep -ox '[[:digit:]]*' pr_number.txt)
+        if [ -z "$pr_number" ]; then
+          echo '::error :: Malformed input, aborting!'
+          exit 1
+        fi
+
+        echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
     - uses: actions/checkout@v3
       with:
         path: velox
@@ -134,7 +140,7 @@ jobs:
 
     - name: "Create a GitHub Status on the contender commit (whether the upload was successful)"
       uses: actions/github-script@v6
-      # if: always()
+      if: ${{ !cancelled() && steps.extract.conclusion != 'failure' }} 
       with:
         script: |
           let url = 'https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}'
